version: '3'
services:
  frontend:
    build: 
      context: ./LiveHomeFront
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./LiveHomeBack
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    volumes:
      # 挂载实际的视频目录到容器内的 /app/videos
      - ./LiveHomeBack/videos:/app/videos
